name: CI
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build:
    name: Integration
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go environment
        uses: actions/setup-go@v2.1.2

      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.14' # The Go version to download (if necessary) and use.
      - run: go version

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v1.2.1
        with:
          version: v1.30.0




      # This step prints an output (time) from the previous step's action.
      - name: test
        run: go test -v -cover -race ./...


