name: CI
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build:
    name: Integration
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go environment
        uses: actions/setup-go@v2.1.2

      # This step prints an output (time) from the previous step's action.
      - name: test
        run: go test -cover -race ./...


